#!/bin/sh

# input parameter:
#   0 - cleanup
#   1 - compile
#   2 - compile & run
#   3 - compile & run & convert
#   4 - compile & run & convert & open
#   5 - compile & run & convert & open & cleanup

# compile C++ v. 11 (Mac)
# param > 0
if [ $1 -gt 0 ]
then
  clang++ -std=c++11 -stdlib=libc++ -o ray-tracer ray-tracer.cpp
fi

# run and time ray tracer
# param > 1
if [ $1 -gt 1 ]
then
  echo "Ray tracer run time:"
  time ./ray-tracer
fi

# cleanup old images
# param = 0 || 5
if [ $1 -eq 0 ]
then
  rm -f images/image.jpg
  rm -f images/imageZ.jpg
else
  if [ $1 -eq 5 ]
  then
    rm -f images/image.jpg
    rm -f images/imageZ.jpg
  fi
fi

# convert images
# param > 2
if [ $1 -gt 2 ]
then
  convert images/image.ppm images/image.jpg
  convert images/imageZ.ppm images/imageZ.jpg
fi

# open images
# param > 3
if [ $1 -gt 3 ]
then
  open -a /Applications/Preview.app/ images/image.jpg
  open -a /Applications/Preview.app/ images/imageZ.jpg
fi

# cleanup
# param = 0 || 5
if [ $1 -eq 0 ]
then
  rm -f images/image.ppm
  rm -f images/imageZ.ppm
  rm -f a.out
  rm -f ray-tracer
else
  if [ $1 -eq 5 ]
  then
    rm -f images/image.ppm
    rm -f images/imageZ.ppm
    rm -f a.out
    rm -f ray-tracer
  fi
fi
